### ISSUE TITLE
Patch doesn't work on latest Synthesis

### ISSUE THREAD

**Issue by Magink666** [tr4wzified/AOSISCSoundPatcher#16] opened 2023-03-18 07:42 UTC
![image](https://user-images.githubusercontent.com/128214221/226092434-994ba0ed-ed86-4610-8395-ba0ef2ecb323.png)

**Comment by Magink666** [comment] 2023-03-18 07:45
![image](https://user-images.githubusercontent.com/128214221/226092611-d9667167-2fc3-451d-978a-37d5507573a7.png)
this one is the latest, sry for sending wrong pics.

**Comment by tr4wzified** [comment] 2023-03-18 09:07
Duplicate of #15, let's discuss there

**Closed as completed by tr4wzified** 2023-03-18 09:07 UTC
